import { NpcId, RouteId, RouteScope, type NPC初始配置 } from './types';

/* 本文件数据来源于《游戏架构目录》，版本号 v1.0.0，生成时间 2026-04-17 16:02 */

export const NPCS_CONFIG: Record<NpcId, NPC初始配置> = {
  [NpcId.YaoLinger]: {
    id: NpcId.YaoLinger,
    姓名: '姚铃儿',
    年龄: 19,
    基础好感值: -20,
    特殊剧情触发标志: '好感>80 && 倾情>60 时帮助玩家谋逆',
    所属路线: RouteId.Lanyinxuguo,
    头像资源路径: '/assets/npcs/yao-linger.png',
  },
  [NpcId.LiuYifang]: {
    id: NpcId.LiuYifang,
    姓名: '柳仪芳',
    年龄: 18,
    基础好感值: 40,
    特殊剧情触发标志: '倾情>60 时帮助玩家争宠并协助谋逆',
    所属路线: RouteId.Lanyinxuguo,
    头像资源路径: '/assets/npcs/liu-yifang.png',
  },
  [NpcId.JiangWanwan]: {
    id: NpcId.JiangWanwan,
    姓名: '江晚晚',
    年龄: 22,
    基础好感值: 10,
    特殊剧情触发标志: false,
    所属路线: RouteId.Lanyinxuguo,
    头像资源路径: '/assets/npcs/jiang-wanwan.png',
  },
  [NpcId.ShenMiaoqing]: {
    id: NpcId.ShenMiaoqing,
    姓名: '沈妙清',
    年龄: 15,
    基础好感值: 70,
    特殊剧情触发标志: '倾情>60 时进入高优先级协助剧情',
    所属路线: RouteId.Fushengrumeng,
    头像资源路径: '/assets/npcs/shen-miaoqing.png',
  },
  [NpcId.ChenWanning]: {
    id: NpcId.ChenWanning,
    姓名: '陈婉宁',
    年龄: 20,
    基础好感值: 0,
    特殊剧情触发标志: '倾情>80 时反向帮助玩家为母家翻案',
    所属路线: RouteId.Yingluoyeting,
    头像资源路径: '/assets/npcs/chen-wanning.png',
  },
  [NpcId.BuZiyou]: {
    id: NpcId.BuZiyou,
    姓名: '布自游',
    年龄: 22,
    基础好感值: 0,
    特殊剧情触发标志: '好感>60 时有概率赠送免费美食；倾情=100 时可一次性协助下毒',
    所属路线: RouteScope.All,
    头像资源路径: '/assets/npcs/bu-ziyou.png',
  },
  [NpcId.JianNing]: {
    id: NpcId.JianNing,
    姓名: '简宁',
    年龄: 24,
    基础好感值: -10,
    特殊剧情触发标志: '好感>80 && 药理>80 时触发假死药事件',
    所属路线: RouteScope.All,
    头像资源路径: '/assets/npcs/jian-ning.png',
  },
  [NpcId.LianQiao]: {
    id: NpcId.LianQiao,
    姓名: '连翘',
    年龄: 18,
    基础好感值: 0,
    特殊剧情触发标志: '好感>60 时赠送稀有曲谱',
    所属路线: RouteScope.All,
    头像资源路径: '/assets/npcs/lian-qiao.png',
  },
  [NpcId.DangYi]: {
    id: NpcId.DangYi,
    姓名: '当一',
    年龄: 18,
    基础好感值: 0,
    特殊剧情触发标志: '好感>80 时帮助玩家假死脱身',
    所属路线: RouteScope.All,
    头像资源路径: '/assets/npcs/dang-yi.png',
  },
  [NpcId.LuAnping]: {
    id: NpcId.LuAnping,
    姓名: '卢安平',
    年龄: 28,
    基础好感值: 80,
    特殊剧情触发标志: '倾情>90 时帮助玩家联络朝中势力并提高官员忠心度',
    所属路线: RouteScope.All,
    头像资源路径: '/assets/npcs/lu-anping.png',
  },
  [NpcId.DuNiang]: {
    id: NpcId.DuNiang,
    姓名: '杜娘',
    年龄: 30,
    基础好感值: 0,
    特殊剧情触发标志: false,
    所属路线: RouteScope.All,
    头像资源路径: '/assets/npcs/du-niang.png',
  },
};

export const NPC_CONFIG_LIST = Object.values(NPCS_CONFIG);
